language: golang

go:
  - 1.4

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

install:
 - go get github.com/vanng822/gopid 
 - go get github.com/stretchr/testify/assert
 - go get github.com/fsnotify/fsnotify

script:
  - go test -v 
